apiVersion: v1
kind: Pod
metadata:
  name: mysecretpod
spec:
  containers:
  - name: mysecretpod
    image: busybox
    args:
      - /bin/sh
      - -c
      - sleep 10; touch /tmp/healthy; sleep 30000
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
   volumes:
   - name: foo
     secret:
       secretName: mysecret2
       items:
       - key: username
         path: /my-group/my-username
       - key: password
         path: /my-group/my-password
