apiVersion: apps/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: httpd-example
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        run: httpd
    spec:
      containers:
      - name: httpd
        # Run this image
        image: httpd
        ports:
        - containerPort: 80
